# Generated by Django 4.0 on 2022-03-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birth',
            field=models.CharField(max_length=64, verbose_name='Дата рождения'),
        ),
    ]
